'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),THREE=require('three');
const source=fs.readFileSync('web/avatar3d-options.js','utf8').replace(/^import .*;$/mg,'').replace(/^export /mg,'');
const context={THREE,console,performance,atob,TextDecoder,Float32Array,Uint32Array,Uint8Array,ArrayBuffer,URL,location:{href:'http://localhost/'}};
vm.runInNewContext(source+';globalThis.Appearance=Avatar3DAppearance;',context);
const scene=new THREE.Scene(),model=new THREE.Group(),geometry=new THREE.BufferGeometry();
geometry.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,1,0,0,0,1,0],3));
const material=new THREE.MeshPhysicalMaterial();material.name='Top_Tia01A_M';
const mesh=new THREE.Mesh(geometry,material);mesh.userData={sourceName:'face',sourcePrimitive:0};model.add(mesh);scene.add(model);
const avatar={scene,model,renderer:{},studioLights:new THREE.Group(),channels:new Map([['mouthSmileLeft',[]]])};
const appearance=new context.Appearance(avatar);avatar.appearance=appearance;
assert.equal(appearance.style,'studio');assert.equal(avatar.renderer.toneMapping,THREE.ACESFilmicToneMapping);
const shader={fragmentShader:'#include <lights_physical_pars_fragment>'};material.onBeforeCompile(shader);assert.match(shader.fragmentShader,/skinEdge/);
appearance.select({lighting:'classic'});assert.equal(avatar.renderer.toneMapping,THREE.NeutralToneMapping);assert.equal(material.onBeforeCompile,appearance.materials.get(material).onBeforeCompile);
const encode=a=>Buffer.from(a.buffer).toString('base64');
const entry={node:'face',primitive:0,count:3,indices:encode(new Uint32Array([0,2])),deltas:encode(new Float32Array([.1,0,0,0,.2,0]))};
const payload=()=>new TextEncoder().encode(JSON.stringify({version:1,meshes:[entry]}));
appearance.activeFace=appearance.decodeFace(payload());appearance.faceRegion='mouth';appearance.faceWeight=-1;
appearance.applyFace({expressionStrength:'1'},false);assert.ok(Math.abs(geometry.attributes.position.array[0]-.1)<1e-6);assert.ok(Math.abs(geometry.attributes.position.array[7]-1.2)<1e-6);
appearance.faceRegion='eyes';appearance.applyFace({expressionStrength:'1'},false,1);assert.equal(geometry.attributes.position.array[0],0);
appearance.faceRegion='mouth';appearance.applyFace({expressionStrength:'1'},true);assert.ok(Math.abs(geometry.attributes.position.array[0]-.02)<1e-6);
appearance.activeFace=[];appearance.applyFace({},false);assert.deepEqual([...geometry.attributes.position.array],[0,0,0,1,0,0,0,1,0]);
entry.indices=encode(new Uint32Array([3]));entry.deltas=encode(new Float32Array([.1,0,0]));assert.throws(()=>appearance.decodeFace(payload()),/Invalid facial/);
const weights=new Map([['mouthSmileLeft',.8],['eyeBlinkLeft',.9],['viseme:aa',.6]]);
appearance.expression(weights,{expression:'neutral',expressionStrength:'1'},true);assert.equal(weights.get('eyeBlinkLeft'),.9);assert.equal(weights.get('viseme:aa'),.6);assert.equal(weights.has('mouthSmileLeft'),false);
appearance.dispose();console.log('Appearance: material restoration, original expression deltas, invalid indices, speech priority and reset passed.');
